# Copyright 2021 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- name: Install CA certificates into keystore
  java_cert:
    executable: "{{ cldr_tls_keytool_path }}"
    cert_alias: "{{ cacert.alias }}"
    cert_path: "{{ cacert.local_path }}"
    keystore_path: "{{ cldr_tls_keystore_path }}"
    keystore_pass: "{{ cldr_tls_key_password }}"
    keystore_type: JKS
    state: present
  loop: "{{ cldr_tls_provider_ca_certificates }}"
  loop_control:
    loop_var: cacert

- name: Install signed certificate reply into keystore
  shell:
    cmd: >
      {{ cldr_tls_keytool_path }}
      -importcert
      -alias "{{ cldr_tls_keystore_alias }}"
      -file "{{ cldr_tls_certificate_path }}"
      -keystore "{{ cldr_tls_keystore_path }}"
      -storepass "{{ cldr_tls_key_password }}"
      -trustcacerts
      -noprompt
  register: keytool_output
  changed_when:
    - "'Certificate reply was installed in keystore' in keytool_output.stderr"
  failed_when:
    - "'Certificate reply was installed in keystore' not in keytool_output.stderr"
    - "'Certificate reply and certificate in keystore are identical' not in keytool_output.stdout"

- name: Install CA certificates into truststore
  java_cert:
    executable: "{{ cldr_tls_keytool_path }}"
    cert_alias: "{{ cacert.alias }}"
    cert_path: "{{ cacert.local_path }}"
    keystore_create: true
    keystore_path: "{{ cldr_tls_truststore_path }}"
    keystore_pass: "{{ cldr_tls_truststore_password }}"
    keystore_type: JKS
    state: present
  loop: "{{ cldr_tls_provider_ca_certificates }}"
  loop_control:
    loop_var: cacert

- name: Update truststore permissions
  file:
    path: "{{ cldr_tls_truststore_path }}"
    owner: root
    group: root
    mode: "0644"

- name: Generate certificate chain file
  shell:
    cmd: "cat {{ cldr_tls_provider_ca_certificates | json_query('[*].local_path') | join(' ') }} > {{ cldr_tls_ca_chain_path }}"
    creates: "{{ cldr_tls_ca_chain_path }}"

- name: Update chain certificate permissions
  file:
    path: "{{ cldr_tls_ca_chain_path }}"
    owner: root
    group: root
    mode: "0644"

- name: Update OS trust stores
  block:
  - copy:
      src: "{{ cacert.local_path }}"
      dest: /etc/pki/ca-trust/source/anchors/
      mode: 0644
      remote_src: yes
    loop: "{{ cldr_tls_provider_ca_certificates }}"
    loop_control:
      loop_var: cacert
  - shell:
      cmd: update-ca-trust extract
  when: ansible_os_family == "RedHat"

- name: Find system cacerts file
  find:
    paths: "{{ cldr_tls_jdk_java_cacerts_search_paths }}"
    pattern: "cacerts"
    follow: yes
    file_type: any
  register: _java_cacerts
  when:
    - cldr_tls_jdk_java_cacerts_location is not defined
    - not cldr_tls_skip_cacerts_import

- fail:
    msg: >-
      Cloudera Manager TLS is enabled but a copy of cacerts cannot be found.
      Please update cldr_tls_jdk_java_cacerts_location with the location of the cacerts file
      or set cldr_tls_skip_cacerts_import to true.
  when:
    - not cldr_tls_skip_cacerts_import
    - cldr_tls_jdk_java_cacerts_location is not defined
    - _java_cacerts.matched == 0
    - "'cloudera_manager' in group_names"

- name: Merge cacerts and the truststore
  shell:
    cmd: >
      {{ cldr_tls_keytool_path }}
      -importkeystore
      -srckeystore "{{ cldr_tls_jdk_java_cacerts_location | default(_java_cacerts.files[0].path) }}"
      -destkeystore "{{ cldr_tls_uber_truststore_path }}"
      -srcstorepass "{{ cldr_tls_jdk_java_cacerts_password }}"
      -deststorepass "{{ cldr_tls_truststore_password }}"
      -noprompt
  when:
    - not cldr_tls_skip_cacerts_import
    - cldr_tls_jdk_java_cacerts_location is defined or _java_cacerts.matched > 0

- name: Merge the truststores
  shell:
    cmd: >
      {{ cldr_tls_keytool_path }}
      -importkeystore
      -srckeystore "{{ cldr_tls_truststore_path }}"
      -destkeystore "{{ cldr_tls_uber_truststore_path }}"
      -srcstorepass "{{ cldr_tls_truststore_password }}"
      -deststorepass "{{ cldr_tls_truststore_password }}"
      -noprompt
